name: couchclient
version: 0.5.2
author: Henri Chen <henrichen@rikulo.org>
description: A Couchbase client library written in Dart language.
homepage: https://github.com/rikulo/couchclient
documentation: http://blog.rikulo.org/posts/2013/May/General/couchclient/
dependencies:
  crypto: any
  logging: any
  memcached_client:
    git: https://github.com/samber/memcached-client.git
dev_dependencies:
  unittest: any
environment:
  sdk: ">=1.4.0"
